---
# config task file for gremlin

- name: Add gremlin user to docker group
  user:
    append: yes
    groups: docker
    name: gremlin
    state: present
  when: gremlin_docker_support

- name: Add login and configure script
  template:
    src: gremlin-config
    dest: /tmp
    mode: a+x

- name: Login and configure Gremlin
  shell: "su -c /tmp/gremlin-config -s /bin/bash gremlin > /tmp/gremlin-bootstrap.out 2>&1"
  when: gremlin_start_after_install
