---
# install task file for gremlin

- name: Add Gremlin repo
  get_url:
    url: https://rpm.gremlininc.com/gremlin.repo
    dest: /etc/yum.repos.d/gremlin.repo

- name: Install Gremlin
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - gremlin
    - gremlind
