#!/bin/bash

set -e

# gremlin vars needed for login
export GREMLIN_IDENTIFIER="{{ gremlin_host_identifier }}"
export GREMLIN_ORG_ID="{{ gremlin_org_id }}"
export GREMLIN_ORG_SECRET="{{ gremlin_org_secret }}"


# login and configure
gremlin config --login --service '{{ gremlin_service_name }}'
